// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://beciomevymwkjaptdigo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJlY2lvbWV2eW13a2phcHRkaWdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg2NzAzMzgsImV4cCI6MjA1NDI0NjMzOH0.o4UnBi9ftXjuzUPzleUnPbzsXtOC06xCfABM4WFIoYg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);